// Generated by npm run content:build; verified SQLite artifact.
export const CONTENT_SHA256 = '06863e76f853042dfe230dafbf9b4a9a38b154c128550c585969eac4c0bad52e';
export const CONTENT_DATABASE_NAME = 'content-06863e76f853042d.sqlite';
