// Generated by npm run content:build; verified SQLite artifact.
export const CONTENT_SHA256 = '1c69ef458597b5e33bfa4aeefbd9fc471194f8d788c68a5802bb5af796a190d7';
export const CONTENT_DATABASE_NAME = 'content-1c69ef458597b5e3.sqlite';
