// Generated by npm run content:build; verified SQLite artifact.
export const CONTENT_SHA256 = 'e02540a50ee8ae9c3d83f00e9ab7f788b536041516c34c80d04775e3ff180cd7';
export const CONTENT_DATABASE_NAME = 'content-e02540a50ee8ae9c.sqlite';
